model:
  type: base_ae_with_init
  model_name: base_ae_with_init
  model_kwargs: 
    init_method: 'orthogonal' 

data:
  train_data_path: ./train
  test_data_path: ./test

training_args:
  seed: 42
  use_cuda: True
  batch_size: 32
  epochs: 6000
  learning_rate: 3.0e-03
  eval_epochs: 500
  output_dir: ./artifacts
  run_name: base_ae_b32_s6000_lr3e3_orthogonal
  b_t: 2