model:
  type: base_ae
  model_name: base_ae
  model_kwargs:

data:
  train_data_path: ./train
  test_data_path: ./test

training_args:
  seed: 42
  use_cuda: True
  batch_size: 64
  epochs: 6000
  learning_rate: 3.0e-03
  eval_epochs: 500
  output_dir: ./artifacts
  run_name: base_ae_b64_s6000_lr3e3
  b_t: 2